services:
  app:
    ports:
      - "80:80" # This is a placeholder, run_local.sh will override this file anyway

  sidecar:
    ports:
      - "8000:8000"
    volumes:
      - ./sidecar/credentials.json:/app/credentials.json
      - ./sidecar/token.json:/app/token.json
